### PR TITLE
merged Pool & PoolToken, some deletions, some comments

### PR DESCRIPTION
**Pull request by elektronaut0815**
Please take a good look at Pool.sol!

### CODE REVIEW

**Comment by loki-sama** [comment]
PoolToken.sol is actually the newer pool contract witch not only works with token vs weth but with all dutchx functionality. So token/token2 and token/weth. SO propably should not be deleted.

**Comment by elektronaut0815** [comment]
PoolToken code is now in Pool.

**Comment by elektronaut0815** [comment]
Pool.test.js still needs work.

**Comment by elektronaut0815** [comment]
Will create a new PR

**Pull request merged**
